apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gcloud-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: $PROJECT_NAME
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
