rbac:
  clusterRole: true
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: gitpod.io/workload_services
              operator: In
              values:
                - 'true'
